config/routes.rb
Rails.application.routes.draw do
  root to: 'facilities#index'
  resources :facilities do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
  # TYPES = ["Restroom", "Nursing Room", "Family Room", "Makeup Room", "Accessible Room"]
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :types, inclusion: { in: ["Restroom", "Nursing Room", "Family Room", "Makeup Room", "Accessible Room"]}
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def add_marker

  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :js

  protect_from_forgery with: :exception
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  responders :flash, :http_cache

  def index
    @facilities = Facility.where.not(latitude: nil, longitude: nil)
    @markers = @facilities.map do |facility|
      {
        lat: facility.latitude,
        lng: facility.longitude
      }
    end
  end

  def show
    @facility = Facility.find(params[:id])
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facilities_params)
    flash[:notice] = "Facility was successfully created." if @facility.save
    respond_with(@facility)
    # respond_to do |format|
    #   if @facility.save
    #     format.js { render 'create' }
    #     redirect_to @facility, notice: "Added Successfully!"
    #   else
    #     format.html { render :new }
    #   end
    # end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def facilities_params
    params.require(:facility).permit(:name, :address, :types)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/create.js.erb
  function addMarker(point){
    var marker = new BMap.Marker(point);
    map.addOverlay(marker);
  }

  // 随机向地图添加25个标注
  var bounds = map.getBounds();
  var sw = bounds.getSouthWest();
  var ne = bounds.getNorthEast();
  var lngSpan = Math.abs(sw.lng - ne.lng);
  var latSpan = Math.abs(ne.lat - sw.lat);
  for (var i = 0; i < 100; i ++) {
    var point = new BMap.Point(sw.lng + lngSpan * (Math.random() * 0.7), ne.lat - latSpan * (Math.random() * 0.7));
    addMarker(point);
  }

app/views/facilities/index.html.erb
<!-- <div class="row"> -->
<div class="iframe-container">
<div id="allmap"></div>
</div>
    <div>
      <p>hi</p>
      <p><%= link_to "Add a public facility", new_facility_path %></p>
    </div>
<script type="text/javascript">
  var map = new BMap.Map("allmap");
  var point = new BMap.Point(121.479102, 31.235929);
  map.centerAndZoom(point, 13);
  map.enableScrollWheelZoom( );
  map.enableInertialDragging();

  map.enableContinuousZoom();

  var size = new BMap.Size(10, 20);
  map.addControl(new BMap.CityListControl({
      anchor: BMAP_ANCHOR_TOP_LEFT,
      offset: size,
      // 切换城市之间事件
      // onChangeBefore: function(){
      //    alert('before');
      // },
      // 切换城市之后事件
      // onChangeAfter:function(){
      //   alert('after');
      // }
  }));

  function addMarker(point){
    var marker = new BMap.Marker(point);
    map.addOverlay(marker);
  }
  // 随机向地图添加25个标注
  var bounds = map.getBounds();
  var sw = bounds.getSouthWest();
  var ne = bounds.getNorthEast();
  var lngSpan = Math.abs(sw.lng - ne.lng);
  var latSpan = Math.abs(ne.lat - sw.lat);
  for (var i = 0; i < 25; i ++) {
    var point = new BMap.Point(sw.lng + lngSpan * (Math.random() * 0.7), ne.lat - latSpan * (Math.random() * 0.7));
    addMarker(point);
  }

</script>

app/views/facilities/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <h1>Add a new facility!</h1>
      <%= simple_form_for @facility do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :types, as: :radio_buttons, collection: ["Restroom", "Nursing Room", "Family Room", "Makeup Room", "Accessible Room"], value_method: :to_sym %>
        <%= f.button :submit %>
      <% end %>
  </div>
</div>

app/views/facilities/show.html.erb
<%= @facility.name %>
<%= @facility.address %>
<%= @facility.types %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WecareWC Map</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merienda+One|Nunito:300,700" rel="stylesheet">
    <style type="text/css">
    body, html,#allmap {width: 100%, height: 90%;overflow: hidden;margin:auto;font-family:"微软雅黑";}
    #l-map{height:100%;width:78%;float:left;border-right:2px solid #bcbcbc;}
    #r-result{height:100%;width:20%;float:left;}
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://api.map.baidu.com/api?v=2.0&ak=3UKSHeiMEMa3dnGG2e3EMTC5WYXRa1TM"%>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=3UKSHeiMEMa3dnGG2e3EMTC5WYXRa1TM"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>hi</h1>